apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:SNJ1/argo-rollouts-demo.git
    path: manifests/blue-green
    targetRevision: HEAD
  destination:
    server: https://34.116.174.116
    namespace: blue-green
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
